apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-frontend
  namespace: demo
  labels:
    app: nodejs-frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-frontend
  template:
    metadata:
      labels:
        app: nodejs-frontend
        tier: frontend
    spec:
      containers:
        - name: nodejs-frontend
          image: k8secops/nodejs:nodejs-main-0000019f-20260628-063921 # {"$imagepolicy": "flux-system:demo-nodejs"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-frontend-config
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
