apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend
  namespace: demo
  labels:
    app: nodejs-frontend
spec:
  type: NodePort
  selector:
    app: nodejs-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
